colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
showLanguageSwitcher = true

[article]
showDate = false
showDateUpdated = false
showReadingTime = false
showWordCount = false