baseURL = "https://matteodimauro.github.io/"
languageCode = "en"
title = "Matteo Di Mauro"
theme = "blowfish"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.it]
    languageName = "Italiano"
    weight = 2
    contentDir = "content/it"